import 'server-only';

import { errors } from '@/lib/api';
import { round, safeDivide } from '@/lib/utils';
import { db } from '@/server/db';

import { getTopicVerdicts } from './analytics-service';

/**
 * Study planner.
 *
 * A student has at most one active plan; tasks hang off it, each scheduled for
 * a day. Auto-generated tasks are derived from the analytics service's weak
 * topics, so the planner recommends revision the evidence actually supports
 * rather than a generic syllabus march.
 */

/** Ensures the student has a plan, creating a sensible default on first visit. */
export async function ensureStudyPlan(userId: string) {
  const existing = await db.studyPlan.findFirst({
    where: { userId, status: 'ACTIVE' },
    select: { id: true },
  });
  if (existing) return existing.id;

  const plan = await db.studyPlan.create({
    data: {
      userId,
      title: 'My study plan',
      description: 'Daily targets and the topics worth your next hour.',
      dailyGoalMinutes: 120,
      weeklyGoalTests: 2,
      monthlyGoalQuestions: 400,
      status: 'ACTIVE',
    },
    select: { id: true },
  });

  return plan.id;
}

export async function getStudyPlan(userId: string) {
  const planId = await ensureStudyPlan(userId);

  const plan = await db.studyPlan.findUniqueOrThrow({
    where: { id: planId },
    select: {
      id: true,
      title: true,
      description: true,
      targetDate: true,
      dailyGoalMinutes: true,
      weeklyGoalTests: true,
      monthlyGoalQuestions: true,
      tasks: {
        orderBy: [{ scheduledFor: 'asc' }, { createdAt: 'asc' }],
        select: {
          id: true,
          title: true,
          description: true,
          type: true,
          scheduledFor: true,
          durationMinutes: true,
          status: true,
          completedAt: true,
          isAutoGenerated: true,
          topic: { select: { id: true, name: true } },
        },
      },
    },
  });

  const completed = plan.tasks.filter((t) => t.status === 'COMPLETED').length;

  // Day boundaries in the server's timezone; the planner is a daily tool, so
  // grouping by calendar day is what a student expects.
  const startOfToday = new Date();
  startOfToday.setHours(0, 0, 0, 0);
  const startOfTomorrow = new Date(startOfToday);
  startOfTomorrow.setDate(startOfTomorrow.getDate() + 1);

  return {
    ...plan,
    stats: {
      total: plan.tasks.length,
      completed,
      pending: plan.tasks.length - completed,
      completionPercent: round(safeDivide(completed, plan.tasks.length) * 100, 0),
    },
    groups: {
      overdue: plan.tasks.filter((t) => t.status !== 'COMPLETED' && t.scheduledFor < startOfToday),
      today: plan.tasks.filter(
        (t) => t.scheduledFor >= startOfToday && t.scheduledFor < startOfTomorrow,
      ),
      upcoming: plan.tasks.filter((t) => t.scheduledFor >= startOfTomorrow),
      completed: plan.tasks.filter((t) => t.status === 'COMPLETED'),
    },
  };
}

export interface CreateTaskParams {
  userId: string;
  title: string;
  description?: string;
  type?: string;
  scheduledFor: Date;
  durationMinutes?: number;
  topicId?: string;
}

export async function createStudyTask(params: CreateTaskParams) {
  const planId = await ensureStudyPlan(params.userId);

  return db.studyTask.create({
    data: {
      planId,
      title: params.title,
      description: params.description ?? null,
      type: params.type ?? 'STUDY',
      scheduledFor: params.scheduledFor,
      durationMinutes: params.durationMinutes ?? 60,
      topicId: params.topicId ?? null,
      status: 'PENDING',
    },
    select: { id: true },
  });
}

/** Flips a task's completion state. Scoped by owner, never by task id alone. */
export async function toggleStudyTask(taskId: string, userId: string) {
  const task = await db.studyTask.findFirst({
    where: { id: taskId, plan: { userId } },
    select: { id: true, status: true },
  });
  if (!task) throw errors.notFound('Task');

  const completing = task.status !== 'COMPLETED';

  await db.studyTask.update({
    where: { id: task.id },
    data: {
      status: completing ? 'COMPLETED' : 'PENDING',
      completedAt: completing ? new Date() : null,
    },
  });

  await refreshPlanCompletion(userId);

  return { completed: completing };
}

export async function deleteStudyTask(taskId: string, userId: string) {
  const deleted = await db.studyTask.deleteMany({
    where: { id: taskId, plan: { userId } },
  });
  if (deleted.count === 0) throw errors.notFound('Task');

  await refreshPlanCompletion(userId);
}

/** Keeps the plan's cached completion percentage in step with its tasks. */
async function refreshPlanCompletion(userId: string) {
  const plan = await db.studyPlan.findFirst({
    where: { userId, status: 'ACTIVE' },
    select: { id: true, _count: { select: { tasks: true } } },
  });
  if (!plan) return;

  const completed = await db.studyTask.count({
    where: { planId: plan.id, status: 'COMPLETED' },
  });

  await db.studyPlan.update({
    where: { id: plan.id },
    data: { completionPercent: round(safeDivide(completed, plan._count.tasks) * 100, 1) },
  });
}

/**
 * Generates revision tasks from the student's weakest topics.
 *
 * Returns zero when there is not enough evidence yet — the planner should stay
 * silent rather than invent a schedule from two answered questions.
 */
export async function generateTasksFromWeakTopics(userId: string) {
  const planId = await ensureStudyPlan(userId);
  const verdicts = await getTopicVerdicts(userId);

  if (verdicts.weak.length === 0) {
    return { created: 0, reason: verdicts.analysedCount === 0 ? 'INSUFFICIENT_DATA' : 'NO_WEAK_TOPICS' };
  }

  // Skip topics that already have an open auto-generated task, so repeated
  // clicks do not pile up duplicates.
  const existing = await db.studyTask.findMany({
    where: { planId, isAutoGenerated: true, status: { not: 'COMPLETED' } },
    select: { topicId: true },
  });
  const covered = new Set(existing.map((t) => t.topicId).filter(Boolean));

  const targets = verdicts.weak.filter((t) => !covered.has(t.id)).slice(0, 5);
  if (targets.length === 0) return { created: 0, reason: 'ALREADY_SCHEDULED' as const };

  // One topic per day, starting today.
  const created = await db.$transaction(
    targets.map((topic, index) => {
      const scheduledFor = new Date();
      scheduledFor.setHours(0, 0, 0, 0);
      scheduledFor.setDate(scheduledFor.getDate() + index);

      return db.studyTask.create({
        data: {
          planId,
          topicId: topic.id,
          title: `Revise ${topic.name}`,
          description: `Your accuracy here is ${topic.accuracy}% across ${topic.total} questions — the lowest of your analysed topics.`,
          type: 'REVISION',
          scheduledFor,
          durationMinutes: 45,
          isAutoGenerated: true,
          status: 'PENDING',
        },
        select: { id: true },
      });
    }),
  );

  await refreshPlanCompletion(userId);

  return { created: created.length, reason: 'OK' as const };
}
