import type { Metadata } from 'next';
import { CalendarCheck, CheckCircle2, ListTodo, Timer } from 'lucide-react';

import { Card, CardContent } from '@/components/ui/card';
import { Progress } from '@/components/ui/progress';
import { StatCard } from '@/components/ui/stat-card';
import { EmptyState } from '@/components/ui/states';
import { TaskBoard } from '@/features/planner/task-board';
import { enforceStudent } from '@/server/auth/guards';
import { getStudyPlan } from '@/server/services/study-planner-service';

export const metadata: Metadata = {
  title: 'Study planner',
  robots: { index: false, follow: false },
};

export const dynamic = 'force-dynamic';

export default async function StudyPlannerPage() {
  const user = await enforceStudent('/study-planner');
  const plan = await getStudyPlan(user.id);

  const serialise = (tasks: typeof plan.groups.today) =>
    tasks.map((task) => ({
      id: task.id,
      title: task.title,
      description: task.description,
      type: task.type,
      scheduledFor: task.scheduledFor.toISOString(),
      durationMinutes: task.durationMinutes,
      status: task.status,
      isAutoGenerated: task.isAutoGenerated,
      topicName: task.topic?.name ?? null,
    }));

  const plannedMinutes = plan.groups.today.reduce((sum, t) => sum + t.durationMinutes, 0);

  return (
    <div className="mx-auto max-w-3xl space-y-6">
      <header>
        <h1 className="text-2xl font-semibold tracking-tight sm:text-3xl">Study planner</h1>
        <p className="mt-1 text-sm text-muted-foreground">
          What you have planned, and what your results suggest you should plan next.
        </p>
      </header>

      <div className="grid gap-4 sm:grid-cols-3">
        <StatCard
          label="Tasks completed"
          value={`${plan.stats.completed} / ${plan.stats.total}`}
          icon={CheckCircle2}
        />
        <StatCard label="Planned today" value={`${plannedMinutes} min`} icon={Timer} hint={`Goal: ${plan.dailyGoalMinutes} min`} />
        <StatCard label="Outstanding" value={plan.stats.pending} icon={ListTodo} />
      </div>

      {/* Daily goal ------------------------------------------------------ */}
      <Card>
        <CardContent className="p-5">
          <div className="flex items-baseline justify-between gap-3 text-sm">
            <span className="font-medium">Today&rsquo;s goal</span>
            <span className="tabular-nums text-muted-foreground">
              {plannedMinutes} / {plan.dailyGoalMinutes} min planned
            </span>
          </div>
          <Progress
            value={(plannedMinutes / plan.dailyGoalMinutes) * 100}
            className="mt-2"
            tone={plannedMinutes >= plan.dailyGoalMinutes ? 'success' : 'primary'}
          />
          <p className="mt-2 text-xs text-muted-foreground">
            This tracks what you have <em>scheduled</em>, not what you have studied — ticking a task
            off is what marks it done.
          </p>
        </CardContent>
      </Card>

      {plan.stats.total === 0 && (
        <EmptyState
          icon={CalendarCheck}
          title="No tasks planned yet"
          description="Add a task below, or let the planner suggest revision from the topics your results show you are weakest on."
          size="sm"
        />
      )}

      <TaskBoard
        groups={{
          overdue: serialise(plan.groups.overdue),
          today: serialise(plan.groups.today),
          upcoming: serialise(plan.groups.upcoming),
          completed: serialise(plan.groups.completed),
        }}
      />
    </div>
  );
}
