'use client';

import * as React from 'react';
import { useRouter } from 'next/navigation';
import { CalendarPlus, Check, Sparkles, Trash2 } from 'lucide-react';
import { toast } from 'sonner';

import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Input, Textarea } from '@/components/ui/input';
import { FormField } from '@/components/ui/label';
import { ApiClientError, api } from '@/lib/api-client';
import { cn, formatDate } from '@/lib/utils';

/**
 * Study task board.
 *
 * Tasks are grouped by when they are due rather than listed flat, because the
 * only question a planner needs to answer on open is "what am I doing today?"
 * — with anything overdue surfaced above it so it cannot be quietly ignored.
 */
export interface PlannerTask {
  id: string;
  title: string;
  description: string | null;
  type: string;
  scheduledFor: string;
  durationMinutes: number;
  status: string;
  isAutoGenerated: boolean;
  topicName: string | null;
}

export interface TaskBoardProps {
  groups: {
    overdue: PlannerTask[];
    today: PlannerTask[];
    upcoming: PlannerTask[];
    completed: PlannerTask[];
  };
}

const TYPE_LABELS: Record<string, string> = {
  STUDY: 'Study',
  REVISION: 'Revision',
  TEST: 'Test',
  PRACTICE: 'Practice',
};

export function TaskBoard({ groups }: TaskBoardProps) {
  const router = useRouter();
  const [busy, setBusy] = React.useState<string | null>(null);
  const [adding, setAdding] = React.useState(false);
  const [generating, setGenerating] = React.useState(false);

  const [title, setTitle] = React.useState('');
  const [notes, setNotes] = React.useState('');
  const [date, setDate] = React.useState(() => new Date().toISOString().slice(0, 10));
  const [minutes, setMinutes] = React.useState(60);

  async function mutate(taskId: string, action: 'toggle' | 'delete') {
    setBusy(taskId);
    try {
      await api.patch('/api/study-tasks', { taskId, action });
      router.refresh();
    } catch (error) {
      toast.error(
        error instanceof ApiClientError ? error.message : 'We could not update that task.',
      );
    } finally {
      setBusy(null);
    }
  }

  async function addTask(event: React.FormEvent) {
    event.preventDefault();
    if (!title.trim()) return;

    setAdding(true);
    try {
      await api.post('/api/study-tasks', {
        title: title.trim(),
        description: notes.trim() || undefined,
        // Midday avoids a task drifting to the previous day in a timezone west
        // of the server.
        scheduledFor: new Date(`${date}T12:00:00`).toISOString(),
        durationMinutes: minutes,
      });

      setTitle('');
      setNotes('');
      toast.success('Task added.');
      router.refresh();
    } catch (error) {
      toast.error(error instanceof ApiClientError ? error.message : 'We could not add that task.');
    } finally {
      setAdding(false);
    }
  }

  async function generate() {
    setGenerating(true);
    try {
      const result = await api.post<{ created: number; reason: string }>(
        '/api/study-tasks?generate=1',
      );
      if (result.created > 0) toast.success(`Added ${result.created} revision tasks.`);
      else toast.info('Nothing new to schedule right now.');
      router.refresh();
    } catch (error) {
      toast.error(error instanceof ApiClientError ? error.message : 'We could not generate tasks.');
    } finally {
      setGenerating(false);
    }
  }

  function renderGroup(label: string, tasks: PlannerTask[], tone?: 'danger') {
    if (tasks.length === 0) return null;

    return (
      <section key={label}>
        <h2
          className={cn(
            'text-sm font-semibold uppercase tracking-wide',
            tone === 'danger' ? 'text-destructive' : 'text-muted-foreground',
          )}
        >
          {label}
          <span className="ml-2 font-normal tabular-nums">{tasks.length}</span>
        </h2>

        <ul className="mt-3 space-y-2.5">
          {tasks.map((task) => {
            const done = task.status === 'COMPLETED';

            return (
              <li
                key={task.id}
                className={cn(
                  'flex items-start gap-3 rounded-xl border bg-card p-4',
                  done ? 'border-border opacity-70' : 'border-border',
                  tone === 'danger' && !done && 'border-destructive/30',
                )}
              >
                <button
                  type="button"
                  onClick={() => mutate(task.id, 'toggle')}
                  disabled={busy === task.id}
                  aria-pressed={done}
                  aria-label={done ? `Reopen ${task.title}` : `Complete ${task.title}`}
                  className={cn(
                    'mt-0.5 flex size-5 shrink-0 items-center justify-center rounded-md border transition-colors',
                    'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2',
                    done
                      ? 'border-success bg-success text-white'
                      : 'border-input hover:border-primary',
                  )}
                >
                  {done && <Check className="size-3.5" strokeWidth={3} aria-hidden="true" />}
                </button>

                <div className="min-w-0 flex-1">
                  <p className={cn('font-medium leading-tight', done && 'line-through')}>
                    {task.title}
                  </p>
                  {task.description && (
                    <p className="mt-1 text-sm leading-relaxed text-muted-foreground">
                      {task.description}
                    </p>
                  )}
                  <p className="mt-1.5 flex flex-wrap items-center gap-2 text-xs text-muted-foreground">
                    <Badge variant="muted" size="sm">
                      {TYPE_LABELS[task.type] ?? task.type}
                    </Badge>
                    <span>{formatDate(task.scheduledFor, 'short')}</span>
                    <span>· {task.durationMinutes} min</span>
                    {task.isAutoGenerated && (
                      <Badge variant="brand" size="sm">
                        <Sparkles aria-hidden="true" />
                        Suggested
                      </Badge>
                    )}
                  </p>
                </div>

                <Button
                  variant="ghost"
                  size="icon-sm"
                  onClick={() => mutate(task.id, 'delete')}
                  disabled={busy === task.id}
                  aria-label={`Delete ${task.title}`}
                  className="shrink-0 text-muted-foreground hover:text-destructive"
                >
                  <Trash2 aria-hidden="true" />
                </Button>
              </li>
            );
          })}
        </ul>
      </section>
    );
  }

  return (
    <div className="space-y-6">
      {/* Add a task ------------------------------------------------------ */}
      <Card>
        <CardContent className="p-5 sm:p-6">
          <div className="flex flex-wrap items-center justify-between gap-3">
            <h2 className="font-semibold tracking-tight">Add a task</h2>
            <Button
              variant="outline"
              size="sm"
              onClick={generate}
              loading={generating}
              loadingText="Analysing…"
            >
              <Sparkles aria-hidden="true" />
              Suggest from my weak topics
            </Button>
          </div>

          <form onSubmit={addTask} className="mt-4 space-y-3">
            <FormField label="What will you work on?" htmlFor="task-title">
              <Input
                value={title}
                onChange={(event) => setTitle(event.target.value)}
                placeholder="e.g. Revise Coulomb's Law"
                maxLength={200}
              />
            </FormField>

            <FormField label="Notes" htmlFor="task-notes" hint="Optional">
              <Textarea
                value={notes}
                onChange={(event) => setNotes(event.target.value)}
                placeholder="Anything you want to remember about this session"
                rows={2}
                maxLength={1000}
              />
            </FormField>

            <div className="grid gap-3 sm:grid-cols-2">
              <FormField label="Date" htmlFor="task-date">
                <Input type="date" value={date} onChange={(event) => setDate(event.target.value)} />
              </FormField>
              <FormField label="Minutes" htmlFor="task-minutes">
                <Input
                  type="number"
                  min={5}
                  max={600}
                  step={5}
                  value={minutes}
                  onChange={(event) => setMinutes(Number(event.target.value))}
                />
              </FormField>
            </div>

            <Button type="submit" loading={adding} disabled={!title.trim()}>
              <CalendarPlus aria-hidden="true" />
              Add task
            </Button>
          </form>
        </CardContent>
      </Card>

      {renderGroup('Overdue', groups.overdue, 'danger')}
      {renderGroup('Today', groups.today)}
      {renderGroup('Upcoming', groups.upcoming)}
      {renderGroup('Completed', groups.completed)}
    </div>
  );
}
